### ISSUE TITLE
Exception: Cycle in causality graph

### ISSUE THREAD

**Issue by mschwerhoff** [viperproject/axiom-profiler#26]
A recent nightly of the axiom profiler crashes with `Found cycle in causality graph!`. The exception occurs regardless of whether or not `Only show instantiations from single check` is ticked while loading the Z3 logfile.

# Z3 logfile

[z3.log](https://github.com/viperproject/axiom-profiler/files/4682546/z3.log)

Created by Z3 4.8.6 on Windows 10.

# Source SMT file

[set_equals_triggers_datatypes.smt2.txt](https://github.com/viperproject/axiom-profiler/files/4682549/set_equals_triggers_datatypes.smt2.txt)

# Exception details

```text
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Found cycle in causality graph!
   at AxiomProfiler.QuantifierModel.Instantiation.get_Depth() in C:\Program Files (x86)\Jenkins\jobs\axiom-profiler-win\workspace\source\QuantifierModel\Instantiation.cs:line 125
   at AxiomProfiler.DAGView.<drawGraphNoFilterQuestion>b__11_0(Instantiation inst) in C:\Program Files (x86)\Jenkins\jobs\axiom-profiler-win\workspace\source\DAGView.cs:line 77
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AxiomProfiler.DAGView.drawGraphNoFilterQuestion() in C:\Program Files (x86)\Jenkins\jobs\axiom-profiler-win\workspace\source\DAGView.cs:line 76
   at AxiomProfiler.AxiomProfiler.loadModel(ParameterConfiguration config) in C:\Program Files (x86)\Jenkins\jobs\axiom-profiler-win\workspace\source\AxiomProfiler.cs:line 264
   at AxiomProfiler.AxiomProfiler.loadModelFromZ3Logfile() in C:\Program Files (x86)\Jenkins\jobs\axiom-profiler-win\workspace\source\AxiomProfiler.cs:line 250
   at AxiomProfiler.AxiomProfiler.LoadZ3Logfile_Click(Object sender, EventArgs e) in C:\Program Files (x86)\Jenkins\jobs\axiom-profiler-win\workspace\source\AxiomProfiler.cs:line 85
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3620.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AxiomProfiler
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///F:/Downloads/Axiom-Profiler-Win/Debug/AxiomProfiler.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3580.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3451.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Msagl.Drawing
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///F:/Downloads/Axiom-Profiler-Win/Debug/Microsoft.Msagl.Drawing.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3620.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.Msagl
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/Downloads/Axiom-Profiler-Win/Debug/Microsoft.Msagl.DLL
----------------------------------------
Microsoft.Msagl.GraphViewerGdi
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///F:/Downloads/Axiom-Profiler-Win/Debug/Microsoft.Msagl.GraphViewerGdi.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by nikswamy** [comment]
I too got this error, after building AxiomProfiler on .NET Framework 4.8 (which is what VS 2022 suggests).

Here's the .smt2 file that triggers it.

[queries-Alex-1.smt2.txt](https://github.com/viperproject/axiom-profiler/files/10118450/queries-Alex-1.smt2.txt)
